#!/usr/bin/env bash
# Displaying login name, uid, and home directory for each account in /etc/passwd
# Account format <login><password><uid><gid><name><home><shell>
# (also see passwd)

while IFS=':' read -r login _ uid _ _ home _
do
   printf '%s:%s:%s\n' "${login}" "${uid}" "${home}"
done </etc/passwd
