#!/usr/bin/env bash
# Displaying the time for 12 h and 59 min

hour=0
while (( hour < 13 ))
do
   echo "Hour: $((hour++))"
   minute=1
   while (( minute < 60 ))
   do
     echo "$((minute++))"
   done
done
