#!/usr/bin/env bash
# Displaying information about the school file

file='school'

if [[ -e ${file} ]]
then
    echo "${file} file exists"
    if [[ -s ${file} ]]
    then
       echo "${file} file is not empty"
    else
       echo "${file} file is empty"
    fi
    if [[ -f ${file} ]]
    then
        echo "${file} is a regular file"
    fi
    else
       eccho "${file} file does not exists"
   fi
